In [25]:
import pickle # For loading model
import difflib
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

In [26]:
!gdown https://drive.google.com/file/d/1hM2BXxXeQemLwr5UWNLvXT7GB1Zmhxac/view?usp=sharing

/usr/local/lib/python3.10/dist-packages/gdown/parse_url.py:35: UserWarning: You specified a Google Drive link that is not the correct link to download a file. You might want to try `--fuzzy` option or the following url: https://drive.google.com/uc?id=1hM2BXxXeQemLwr5UWNLvXT7GB1Zmhxac
  warnings.warn(
Downloading...
From: https://drive.google.com/file/d/1hM2BXxXeQemLwr5UWNLvXT7GB1Zmhxac/view?usp=sharing
To: /content/view?usp=sharing
84.2kB [00:00, 33.7MB/s]


In [27]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [28]:
df = pd.read_csv('/content/wisata_bandung_ .csv')
df

category                                               tags  \
0           Cagar Alam      Cagar Alam, Bandung, Jauh dari Bandara, Murah   
1               Budaya        Budaya, Bandung, Dekat dari Bandung, Gratis   
2               Budaya         Budaya, Bandung, Dekat dari Bandung, Murah   
3        Taman Hiburan  Taman Hiburan, Bandung, Dekat dari Bandung, Mahal   
4           Cagar Alam     Cagar Alam, Bandung, Dekat dari Bandara, Murah   
..                 ...                                                ...   
70          Cagar Alam      Cagar Alam, Bandung, Jauh dari Bandara, Murah   
71       Taman Hiburan  Taman HIburan, Bandung, Dekat dari Bandara, Gr...   
72  Pusat Perbelanjaan  Pusat Perbelanjaan, Bandung, Dekat dari Bandar...   
73              Budaya        Budaya, Bandung, Dekat dari Bandara, Gratis   
74              Budaya        Budaya, Bandung, Dekat dari Bandara, Gratis   

                                                image  weekend_price  \
0   https://akcdn.detik.net.id/visual/2017/12/26/7...          30000   
1   https://www.indonesia.travel/content/dam/indtr...              0   
2   https://upload.wikimedia.org/wikipedia/commons...           5000   
3   https://www.hu-pakuan.com/media/original/20102...         280000   
4   https://assets-a1.kompasiana.com/items/album/2...          15000   
..                                                ...            ...   
70  https://i.ytimg.com/vi/ZLeda7UyBOk/maxresdefau...           7500   
71  https://cdn.idntimes.com/content-images/commun...              0   
72  https://pict.sindonews.net/dyn/620/pena/news/2...              0   
73  https://img.bandung.go.id/images/news/2017/01/...              0   
74  https://www.sarasvati.co.id/wp-content/uploads...              0   

    weekday_price distance  rating                       place_name     city  \
0           30000     jauh     4.5          Gunung Tangkuban Perahu  Bandung   
1               0    dekat     4.7                      Jalan Braga  Bandung   
2            5000    dekat     4.6                      Gedung Sate  Bandung   
3          280000    dekat     4.5             Trans Studio Bandung  Bandung   
4           15000    dekat     4.5  Taman Hutan Raya Ir. H. Djuanda  Bandung   
..            ...      ...     ...                              ...      ...   
70           7500     jauh     4.0                Curug Cilengkrang  Bandung   
71              0    dekat     4.6                Jembatan Pasupati  Bandung   
72              0    dekat     4.3                       Pasar Baru  Bandung   
73              0    dekat     4.6            Taman Sejarah Bandung  Bandung   
74              0    dekat     4.4            Roemah Seni Sarasvati  Bandung   

                                          description  
0   Gunung Tangkuban Parahu adalah salah satu gunu...  
1   Jalan Braga adalah nama sebuah jalan utama di ...  
2   Gedung Sate, dengan ciri khasnya berupa orname...  
3   Trans Studio Bandung adalah kawasan wisata ter...  
4   Taman Hutan Raya Ir. H. Djuanda (Tahura Djuand...  
..                                                ...  
70  Curug Cilengkrang bisa menjadi pilihan tujuan ...  
71  Jembatan Pasupati atau Jalan Layang Pasupati a...  
72  Pasar Baru adalah kawasan perdagangan yang ber...  
73  Taman Sejarah Bandung adalah taman yang terlet...  
74  Roemah Seni Sarasvati adalah sebuah galeri yan...  

[75 rows x 10 columns]

In [29]:
df_filter = df[['place_name', 'tags', 'description']]
df_filter.head()

place_name  \
0          Gunung Tangkuban Perahu   
1                      Jalan Braga   
2                      Gedung Sate   
3             Trans Studio Bandung   
4  Taman Hutan Raya Ir. H. Djuanda   

                                                tags  \
0      Cagar Alam, Bandung, Jauh dari Bandara, Murah   
1        Budaya, Bandung, Dekat dari Bandung, Gratis   
2         Budaya, Bandung, Dekat dari Bandung, Murah   
3  Taman Hiburan, Bandung, Dekat dari Bandung, Mahal   
4     Cagar Alam, Bandung, Dekat dari Bandara, Murah   

                                         description  
0  Gunung Tangkuban Parahu adalah salah satu gunu...  
1  Jalan Braga adalah nama sebuah jalan utama di ...  
2  Gedung Sate, dengan ciri khasnya berupa orname...  
3  Trans Studio Bandung adalah kawasan wisata ter...  
4  Taman Hutan Raya Ir. H. Djuanda (Tahura Djuand...

In [30]:
df_filter.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   place_name   75 non-null     object
 1   tags         75 non-null     object
 2   description  75 non-null     object
dtypes: object(3)
memory usage: 1.9+ KB


In [31]:
df.shape

(75, 10)

In [32]:
df_filter = df_filter.dropna(axis='rows')
df_filter = df_filter.fillna('unknown')
df_filter

place_name  \
0           Gunung Tangkuban Perahu   
1                       Jalan Braga   
2                       Gedung Sate   
3              Trans Studio Bandung   
4   Taman Hutan Raya Ir. H. Djuanda   
..                              ...   
70                Curug Cilengkrang   
71                Jembatan Pasupati   
72                       Pasar Baru   
73            Taman Sejarah Bandung   
74            Roemah Seni Sarasvati   

                                                 tags  \
0       Cagar Alam, Bandung, Jauh dari Bandara, Murah   
1         Budaya, Bandung, Dekat dari Bandung, Gratis   
2          Budaya, Bandung, Dekat dari Bandung, Murah   
3   Taman Hiburan, Bandung, Dekat dari Bandung, Mahal   
4      Cagar Alam, Bandung, Dekat dari Bandara, Murah   
..                                                ...   
70      Cagar Alam, Bandung, Jauh dari Bandara, Murah   
71  Taman HIburan, Bandung, Dekat dari Bandara, Gr...   
72  Pusat Perbelanjaan, Bandung, Dekat dari Bandar...   
73        Budaya, Bandung, Dekat dari Bandara, Gratis   
74        Budaya, Bandung, Dekat dari Bandara, Gratis   

                                          description  
0   Gunung Tangkuban Parahu adalah salah satu gunu...  
1   Jalan Braga adalah nama sebuah jalan utama di ...  
2   Gedung Sate, dengan ciri khasnya berupa orname...  
3   Trans Studio Bandung adalah kawasan wisata ter...  
4   Taman Hutan Raya Ir. H. Djuanda (Tahura Djuand...  
..                                                ...  
70  Curug Cilengkrang bisa menjadi pilihan tujuan ...  
71  Jembatan Pasupati atau Jalan Layang Pasupati a...  
72  Pasar Baru adalah kawasan perdagangan yang ber...  
73  Taman Sejarah Bandung adalah taman yang terlet...  
74  Roemah Seni Sarasvati adalah sebuah galeri yan...  

[75 rows x 3 columns]

## Recommendation by Genre

In [33]:
df_Tags = df.tags
df_Tags

0         Cagar Alam, Bandung, Jauh dari Bandara, Murah
1           Budaya, Bandung, Dekat dari Bandung, Gratis
2            Budaya, Bandung, Dekat dari Bandung, Murah
3     Taman Hiburan, Bandung, Dekat dari Bandung, Mahal
4        Cagar Alam, Bandung, Dekat dari Bandara, Murah
                            ...                        
70        Cagar Alam, Bandung, Jauh dari Bandara, Murah
71    Taman HIburan, Bandung, Dekat dari Bandara, Gr...
72    Pusat Perbelanjaan, Bandung, Dekat dari Bandar...
73          Budaya, Bandung, Dekat dari Bandara, Gratis
74          Budaya, Bandung, Dekat dari Bandara, Gratis
Name: tags, Length: 75, dtype: object

In [34]:
def remove_brackets(data):
    data = str(data).lower()
    data = data.replace(',', '')
    data = data.replace("'", '')
    return data

df_Tags = df_Tags.apply(remove_brackets)
df_Tags

0            cagar alam bandung jauh dari bandara murah
1              budaya bandung dekat dari bandung gratis
2               budaya bandung dekat dari bandung murah
3        taman hiburan bandung dekat dari bandung mahal
4           cagar alam bandung dekat dari bandara murah
                            ...                        
70           cagar alam bandung jauh dari bandara murah
71      taman hiburan bandung dekat dari bandara gratis
72    pusat perbelanjaan bandung dekat dari bandara ...
73             budaya bandung dekat dari bandara gratis
74             budaya bandung dekat dari bandara gratis
Name: tags, Length: 75, dtype: object

In [35]:
vector_tfidf = TfidfVectorizer()
result_tfidf = vector_tfidf.fit_transform(df_Tags)

In [36]:
result_arr = result_tfidf.toarray()
result_arr

array([[0.48342215, 0.23212025, 0.22021389, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.48037909, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.4985895 , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.14586238, 0.13838053, ..., 0.64175162, 0.        ,
        0.        ],
       [0.        , 0.26821155, 0.25445393, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.26821155, 0.25445393, ..., 0.        , 0.        ,
        0.        ]])

In [37]:
vector_tfidf.get_feature_names_out()

array(['alam', 'bandara', 'bandung', 'budaya', 'cagar', 'dari', 'dekat',
       'gratis', 'hiburan', 'ibadah', 'jauh', 'mahal', 'murah',
       'perbelanjaan', 'pusat', 'taman', 'tempat'], dtype=object)

In [38]:
# choose one or more category
test = 'cagar alam', 'budaya', 'taman hiburan', 'tempat ibadah', 'pusat perbelanjaan', 'alam dekat gratis'


In [39]:
test = 'alam dekat gratis'
test_arr = vector_tfidf.transform([test])
test_arr = test_arr.toarray()
test_arr

array([[0.66445596, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.40612127, 0.62734663, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])

In [40]:
result = {}
for id, vector in enumerate(result_arr):
    cosine_val = cosine_similarity([result_arr[id]], test_arr)
    result[id] = cosine_val

result_desc = dict(sorted(result.items(), key=lambda item: item[1], reverse=True))

top_n = 5

for n, place_id in enumerate(result_desc):
    if n > 4:
        break
    print(df_filter.iloc[place_id]['place_name'])

Babakan Siliwangi City Forest Path Bandung
Caringin Tilu
Taman Hutan Raya Ir. H. Djuanda
Kebun Binatang Bandung
Tebing Karaton


##save data

In [46]:
# Save dataframe
pickle.dump(result_arr, open('resulttfidf_wisata.pkl', 'wb'))

In [47]:
resulttfidf_wisata = pickle.load(open('resulttfidf_wisata.pkl','rb'))
resulttfidf_wisata

array([[0.48342215, 0.23212025, 0.22021389, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.48037909, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.4985895 , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.14586238, 0.13838053, ..., 0.64175162, 0.        ,
        0.        ],
       [0.        , 0.26821155, 0.25445393, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.26821155, 0.25445393, ..., 0.        , 0.        ,
        0.        ]])

In [48]:
pickle.dump(df, open('df.pkl', 'wb'))

In [49]:
pickle.dump(vector_tfidf, open('vector_tfidf.pkl', 'wb'))

In [50]:
vectortfidf_wisata = pickle.load(open('vector_tfidf.pkl','rb'))
vectortfidf_wisata

TfidfVectorizer()