In [189]:
import pickle
import difflib
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

In [190]:
!gdown https://drive.google.com/file/d/1hM2BXxXeQemLwr5UWNLvXT7GB1Zmhxac/view?usp=sharing

/usr/local/lib/python3.10/dist-packages/gdown/parse_url.py:35: UserWarning: You specified a Google Drive link that is not the correct link to download a file. You might want to try `--fuzzy` option or the following url: https://drive.google.com/uc?id=1hM2BXxXeQemLwr5UWNLvXT7GB1Zmhxac
  warnings.warn(
Downloading...
From: https://drive.google.com/file/d/1hM2BXxXeQemLwr5UWNLvXT7GB1Zmhxac/view?usp=sharing
To: /content/view?usp=sharing
84.7kB [00:00, 55.0MB/s]


In [191]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [192]:
df = pd.read_csv('/content/drive/MyDrive/MSIB/wisata_bandung.csv')
df

category                                               tags  \
0      Cagar Alam  Cagar Alam, Sedang, Gunung, Gunung Tangkuban P...   
1          Budaya  Budaya, Dekat dari Bandung, Budaya Gratis, Bra...   
2          Budaya     Budaya, Dekat dari Bandung, Murah, Gedung Sate   
3   Taman Hiburan  Taman Hiburan, Dekat dari Bandung, Mahal, TSM,...   
4      Cagar Alam  Cagar Alam, Bandung, Dekat, Murah, Taman Hutan...   
..            ...                                                ...   
82     Cagar Alam  Gunung Patuha, Gunung, Murah, Bandung, Alam, C...   
83     Cagar Alam  Gunung Burangrang, Cagar Alam, Alam, Murah, Ba...   
84     Cagar Alam  Gunung Manglayang, Cagar Alam, Alam, Murah, Ba...   
85     Cagar Alam  Lactasari Mini Farm dan Bird Park, Cagar Alam,...   
86     Cagar Alam  Zoomanji Bandung, Cagar Alam, Kebun Binatang, ...   

                                                image   price distance  \
0   https://akcdn.detik.net.id/visual/2017/12/26/7...   30000     jauh   
1   https://www.indonesia.travel/content/dam/indtr...       0    dekat   
2   https://upload.wikimedia.org/wikipedia/commons...    5000    dekat   
3   https://www.hu-pakuan.com/media/original/20102...  280000    dekat   
4   https://assets-a1.kompasiana.com/items/album/2...   15000    dekat   
..                                                ...     ...      ...   
82  https://pariwisataindonesia.id/wp-content/uplo...   10000    dekat   
83  https://superlive.id/storage/superadventure/20...   15000     jauh   
84  https://upload.wikimedia.org/wikipedia/commons...   10000     jauh   
85  https://www.pegipegi.com/travel/wp-content/upl...   60000     jauh   
86  https://www.bandungsatu.com/wp-content/uploads...   35000     jauh   

    rating                         place_name  \
0      4.5            Gunung Tangkuban Perahu   
1      4.7                        Jalan Braga   
2      4.6                        Gedung Sate   
3      4.5               Trans Studio Bandung   
4      4.5    Taman Hutan Raya Ir. H. Djuanda   
..     ...                                ...   
82     4.5                      Gunung Patuha   
83     4.5                  Gunung Burangrang   
84     4.5                 Gunung Manglayang    
85     4.3  Lactasari Mini Farm dan Bird Park   
86     4.3                   Zoomanji Bandung   

                                                 city  \
0   Cikahuripan, Kec. Lembang, Kabupaten Bandung B...   
1        Kec. Sumur Bandung, Kota Bandung, Jawa Barat   
2   Jl. Diponegoro No.22, Citarum, Kec. Bandung We...   
3   Jl. Gatot Subroto No.289A, Cibangkong, Kec. Ba...   
4   Kompleks Tahura, Jl. Ir. H. Juanda No.99, Cibu...   
..                                                ...   
82             Ciwidey, Bandung Jawa Barat, Indonesia   
83                            Barat Laut Bandung Raya   
84                                      Bandung Timur   
85  Paris Van Java, Jl. Sukajadi No.131-139, Ciped...   
86  Jl. Dago Giri No.KM 2, RW.2, Mekarwangi, Kec. ...   

                                          description  
0   Gunung Tangkuban Parahu adalah salah satu gunu...  
1   Jalan Braga adalah nama sebuah jalan utama di ...  
2   Gedung Sate, dengan ciri khasnya berupa orname...  
3   Trans Studio Bandung adalah kawasan wisata ter...  
4   Taman Hutan Raya Ir. H. Djuanda (Tahura Djuand...  
..                                                ...  
82  Gunung Patuha terletak di kawasan Ciwidey, Kab...  
83  Terletak di kawasan barat laut Bandung Raya, G...  
84  Gunung Manglayang, yang berada di Bandung timu...  
85  Lactasari Mini Farm dan Bird Park adalah tempa...  
86  Zoomanji Bandung menawarkan konsep yang berbed...  

[87 rows x 9 columns]

In [193]:
df_filter = df[['place_name', 'tags', 'description']]
df_filter.head()

place_name  \
0          Gunung Tangkuban Perahu   
1                      Jalan Braga   
2                      Gedung Sate   
3             Trans Studio Bandung   
4  Taman Hutan Raya Ir. H. Djuanda   

                                                tags  \
0  Cagar Alam, Sedang, Gunung, Gunung Tangkuban P...   
1  Budaya, Dekat dari Bandung, Budaya Gratis, Bra...   
2     Budaya, Dekat dari Bandung, Murah, Gedung Sate   
3  Taman Hiburan, Dekat dari Bandung, Mahal, TSM,...   
4  Cagar Alam, Bandung, Dekat, Murah, Taman Hutan...   

                                         description  
0  Gunung Tangkuban Parahu adalah salah satu gunu...  
1  Jalan Braga adalah nama sebuah jalan utama di ...  
2  Gedung Sate, dengan ciri khasnya berupa orname...  
3  Trans Studio Bandung adalah kawasan wisata ter...  
4  Taman Hutan Raya Ir. H. Djuanda (Tahura Djuand...

In [194]:
df_filter.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   place_name   87 non-null     object
 1   tags         87 non-null     object
 2   description  87 non-null     object
dtypes: object(3)
memory usage: 2.2+ KB


In [195]:
df.shape

(87, 9)

In [196]:
df_filter = df_filter.dropna(axis='rows')
df_filter = df_filter.fillna('unknown')
df_filter

place_name  \
0             Gunung Tangkuban Perahu   
1                         Jalan Braga   
2                         Gedung Sate   
3                Trans Studio Bandung   
4     Taman Hutan Raya Ir. H. Djuanda   
..                                ...   
82                      Gunung Patuha   
83                  Gunung Burangrang   
84                 Gunung Manglayang    
85  Lactasari Mini Farm dan Bird Park   
86                   Zoomanji Bandung   

                                                 tags  \
0   Cagar Alam, Sedang, Gunung, Gunung Tangkuban P...   
1   Budaya, Dekat dari Bandung, Budaya Gratis, Bra...   
2      Budaya, Dekat dari Bandung, Murah, Gedung Sate   
3   Taman Hiburan, Dekat dari Bandung, Mahal, TSM,...   
4   Cagar Alam, Bandung, Dekat, Murah, Taman Hutan...   
..                                                ...   
82  Gunung Patuha, Gunung, Murah, Bandung, Alam, C...   
83  Gunung Burangrang, Cagar Alam, Alam, Murah, Ba...   
84  Gunung Manglayang, Cagar Alam, Alam, Murah, Ba...   
85  Lactasari Mini Farm dan Bird Park, Cagar Alam,...   
86  Zoomanji Bandung, Cagar Alam, Kebun Binatang, ...   

                                          description  
0   Gunung Tangkuban Parahu adalah salah satu gunu...  
1   Jalan Braga adalah nama sebuah jalan utama di ...  
2   Gedung Sate, dengan ciri khasnya berupa orname...  
3   Trans Studio Bandung adalah kawasan wisata ter...  
4   Taman Hutan Raya Ir. H. Djuanda (Tahura Djuand...  
..                                                ...  
82  Gunung Patuha terletak di kawasan Ciwidey, Kab...  
83  Terletak di kawasan barat laut Bandung Raya, G...  
84  Gunung Manglayang, yang berada di Bandung timu...  
85  Lactasari Mini Farm dan Bird Park adalah tempa...  
86  Zoomanji Bandung menawarkan konsep yang berbed...  

[87 rows x 3 columns]

## Pemodelan

In [197]:
df_Tags = df.tags
df_Tags

0     Cagar Alam, Sedang, Gunung, Gunung Tangkuban P...
1     Budaya, Dekat dari Bandung, Budaya Gratis, Bra...
2        Budaya, Dekat dari Bandung, Murah, Gedung Sate
3     Taman Hiburan, Dekat dari Bandung, Mahal, TSM,...
4     Cagar Alam, Bandung, Dekat, Murah, Taman Hutan...
                            ...                        
82    Gunung Patuha, Gunung, Murah, Bandung, Alam, C...
83    Gunung Burangrang, Cagar Alam, Alam, Murah, Ba...
84    Gunung Manglayang, Cagar Alam, Alam, Murah, Ba...
85    Lactasari Mini Farm dan Bird Park, Cagar Alam,...
86    Zoomanji Bandung, Cagar Alam, Kebun Binatang, ...
Name: tags, Length: 87, dtype: object

In [198]:
def remove_brackets(data):
    data = str(data).lower()
    data = data.replace(',', '')
    data = data.replace("'", '')
    return data

df_Tags = df_Tags.apply(remove_brackets)
df_Tags

0      cagar alam sedang gunung gunung tangkuban parahu
1     budaya dekat dari bandung budaya gratis braga ...
2           budaya dekat dari bandung murah gedung sate
3     taman hiburan dekat dari bandung mahal tsm tra...
4     cagar alam bandung dekat murah taman hutan ray...
                            ...                        
82    gunung patuha gunung murah bandung alam cagar ...
83    gunung burangrang cagar alam alam murah bandun...
84    gunung manglayang cagar alam alam murah bandun...
85    lactasari mini farm dan bird park cagar alam k...
86    zoomanji bandung cagar alam kebun binatang hew...
Name: tags, Length: 87, dtype: object

In [199]:
vector_tfidf = TfidfVectorizer()
result_tfidf = vector_tfidf.fit_transform(df_Tags)

result_arr = result_tfidf.toarray()
result_arr

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.53013368]])

In [200]:
vector_tfidf.get_feature_names_out()

array(['ade', 'africa', 'afrika', 'air', 'al', 'alam', 'amazing', 'anak',
       'and', 'angklung', 'angkringan', 'art', 'artha', 'asia', 'atas',
       'baduga', 'bakery', 'balai', 'bambu', 'bandara', 'bandung', 'batu',
       'belanda', 'bermain', 'binatang', 'bintang', 'bird', 'braga',
       'budaya', 'bukit', 'bunga', 'burangrang', 'cafe', 'cagar',
       'camping', 'cepat', 'china', 'cikole', 'citatah', 'city',
       'citylight', 'ciumbuleuit', 'ciwidey', 'creative', 'curug', 'dago',
       'dan', 'dari', 'dekat', 'dewi', 'dimensi', 'djuanda', 'dreampark',
       'dunia', 'dusun', 'ecopark', 'edelweis', 'estetik', 'farm',
       'feeding', 'forest', 'fossil', 'foto', 'garden', 'gedung',
       'geologi', 'gereja', 'gkim', 'glamping', 'goa', 'gondola',
       'gratis', 'great', 'ground', 'gua', 'gunung', 'haji', 'hall',
       'harimau', 'hewan', 'hiburan', 'hobbit', 'house', 'hutan',
       'ibadah', 'im', 'interaktif', 'ir', 'irma', 'istana', 'itb',
       'jabbar', 'jalan', 'j

In [201]:
# choose one or more category
test = 'alam terdekat gratis'

In [202]:
test = 'alam sedang'
test_arr = vector_tfidf.transform([test])
test_arr = test_arr.toarray()
test_arr

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.5623888 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [203]:
result = {}
for id, vector in enumerate(result_arr):
    cosine_val = cosine_similarity([result_arr[id]], test_arr)
    result[id] = cosine_val

result_desc = dict(sorted(result.items(), key=lambda item: item[1], reverse=True))

top_n = 5

for n, place_id in enumerate(result_desc):
    if n > 4:
        break
    print(df_filter.iloc[place_id]['place_name'])

Bukit Bintang
Curug Cipanas
Jendela Alam
Selasar Sunaryo Art Space
Gunung Tangkuban Perahu


##save data / model


In [204]:
# Save dataframe
pickle.dump(result_arr, open('resulttfidf_wisata.pkl', 'wb'))

In [205]:
resulttfidf_wisata = pickle.load(open('resulttfidf_wisata.pkl','rb'))
resulttfidf_wisata

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.53013368]])

In [206]:
pickle.dump(df, open('df.pkl', 'wb'))

In [207]:
pickle.dump(vector_tfidf, open('vector_tfidf.pkl', 'wb'))

In [208]:
vectortfidf_wisata = pickle.load(open('vector_tfidf.pkl','rb'))
vectortfidf_wisata

TfidfVectorizer()